server:
  address: 0.0.0.0
  port: 8082


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/open_source_ens?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: open_source
    password: rAdNqzGvaX0JNcsETbh2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

  redis:
    timeout: 6000
    database: 0
    host: 127.0.0.1
    password: Utt*@CX$UtdU
    port: 6379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 3


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0

logging:
  level:
    root: info
    org.springframework.security: debug

topic:
  secretKey:
    value: kjgy%$uBoMOHCJeOw%@T4cEN6XjnouGt
  pathKey: Uo1K9ULR%YrwMQxUEVw!KPlNolqs5MeI
  secondPwdKey: f02I$*H!Nf^19^pdez9DT28@&FEf%JPl
  secondPwdLimitLength: 12
  expireDay: 7
  readSecond: 300
  tokenSecond: 3600


asyncThreadPool:
  corePoolSize: 10
  maxPoolSize: 30
  queueCapacity: 10
  keepAliveSeconds: 300
  awaitTerminationSeconds: 300
  threadNamePrefix: encryptAsync

